# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/inputs/base"
require "logstash/namespace"
require "logstash-input-java_input_debezium_jars"
require "java"

class LogStash::Inputs::JavaInputDebezium < LogStash::Inputs::Base
  config_name "java_input_debezium"

  def self.javaClass() Java::org.logstashplugins.JavaInputDebezium.java_class; end
end
